// Package render turns validated Temper inputs into a complete config bundle.
// It is deliberately pure: callers provide bytes and paths, and it performs
// no filesystem or network access.
package render

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/temper-sh/temper/internal/artifactset"
	"github.com/temper-sh/temper/internal/lockfile"
	"github.com/temper-sh/temper/internal/manifest"
)

type Inputs struct {
	Manifest       manifest.Document
	Lock           lockfile.Document
	Mode           string
	Root           string
	PiModelsBase   []byte
	PiSettingsBase []byte
}

type Artifact struct {
	Path string
	Data []byte
}

type Bundle struct {
	Mode      string
	Artifacts []Artifact
}

func (b Bundle) Digest() string {
	hash := sha256.New()
	artifacts := append([]Artifact(nil), b.Artifacts...)
	sort.Slice(artifacts, func(i, j int) bool { return artifacts[i].Path < artifacts[j].Path })
	for _, artifact := range artifacts {
		writeHashPart(hash, []byte(artifact.Path))
		writeHashPart(hash, artifact.Data)
	}
	return hex.EncodeToString(hash.Sum(nil))
}

func Build(inputs Inputs) (Bundle, error) {
	if err := inputs.Manifest.Validate(); err != nil {
		return Bundle{}, err
	}
	if err := inputs.Lock.Validate(); err != nil {
		return Bundle{}, err
	}
	if !filepath.IsAbs(inputs.Root) || filepath.Clean(inputs.Root) != inputs.Root || inputs.Root == string(filepath.Separator) {
		return Bundle{}, errors.New("render root must be a clean absolute path other than filesystem root")
	}
	if strings.ContainsAny(inputs.Root, "\r\n\x00") {
		return Bundle{}, errors.New("render root contains an unsupported control character")
	}

	mode, err := inputs.Manifest.Mode(inputs.Mode)
	if err != nil {
		return Bundle{}, err
	}
	resolved, err := resolveMembers(inputs.Manifest, inputs.Lock, mode, inputs.Root)
	if err != nil {
		return Bundle{}, err
	}

	bundle := Bundle{
		Mode: inputs.Mode,
		Artifacts: []Artifact{{
			Path: "llama-swap/config.yaml",
			Data: renderLlamaSwap(inputs.Manifest.Defaults, resolved),
		}},
	}

	if contains(mode.Harnesses, "pi") {
		models, err := renderPiModels(inputs.PiModelsBase, resolved)
		if err != nil {
			return Bundle{}, fmt.Errorf("render pi/models.json: %w", err)
		}
		settings, err := renderPiSettings(inputs.PiSettingsBase, resolved)
		if err != nil {
			return Bundle{}, fmt.Errorf("render pi/settings.json: %w", err)
		}
		bundle.Artifacts = append(bundle.Artifacts,
			Artifact{Path: "pi/models.json", Data: models},
			Artifact{Path: "pi/settings.json", Data: settings},
		)
	}

	return bundle, nil
}

type resolvedMember struct {
	ID        string
	Layout    manifest.Layout
	Member    manifest.Member
	Placement string
	ModelPath string
	PatchPath string
}

func resolveMembers(document manifest.Document, lock lockfile.Document, mode manifest.Mode, root string) ([]resolvedMember, error) {
	var resolved []resolvedMember
	placements := []struct {
		name    string
		members []manifest.Member
	}{
		{name: "resident", members: mode.Members.Resident},
		{name: "on_demand", members: mode.Members.OnDemand},
	}

	for _, placement := range placements {
		for _, member := range placement.members {
			layout := document.Layouts[member.Layout]
			entry, ok := lock.Entry(member.Layout)
			if !ok {
				return nil, fmt.Errorf("layout %q has no lock entry", member.Layout)
			}
			set, err := artifactset.New(root, member.Layout, layout, entry, document.Patches)
			if err != nil {
				return nil, err
			}

			item := resolvedMember{
				ID:        member.Layout,
				Layout:    layout,
				Member:    member,
				Placement: placement.name,
				ModelPath: filepath.Join(set.Path(), "model", layout.Model.File),
			}
			if layout.ChatTemplate != "" {
				patch := document.Patches[layout.ChatTemplate]
				item.PatchPath = filepath.Join(set.Path(), "patches", layout.ChatTemplate, patch.File)
			}
			resolved = append(resolved, item)
		}
	}
	return resolved, nil
}

func renderLlamaSwap(defaults manifest.Defaults, members []resolvedMember) []byte {
	var output strings.Builder
	output.WriteString("# GENERATED by temper — edit manifest.yaml instead\n")
	output.WriteString("healthCheckTimeout: 300\n")
	output.WriteString("startPort: 10001\n")
	fmt.Fprintf(&output, "globalTTL: %d\n", defaults.TTL)
	output.WriteString("captureBuffer: 15                 # request/response capture for the /ui inspector\n")

	var preloads []string
	for _, member := range members {
		if member.Member.Preload {
			preloads = append(preloads, member.ID)
		}
	}
	if len(preloads) > 0 {
		output.WriteString("\nhooks:\n  on_startup:\n    preload:\n")
		for _, id := range preloads {
			fmt.Fprintf(&output, "      - %s\n", strconv.Quote(id))
		}
	}

	output.WriteString("\nmodels:")
	if len(members) == 0 {
		output.WriteString(" {}\n")
	} else {
		output.WriteByte('\n')
	}
	for _, member := range members {
		fmt.Fprintf(&output, "  %s:\n", strconv.Quote(member.ID))
		fmt.Fprintf(&output, "    name: %s\n", strconv.Quote(member.Layout.DisplayName))
		output.WriteString("    cmd: >\n")
		for _, argumentLine := range llamaCommand(member) {
			fmt.Fprintf(&output, "      %s\n", argumentLine)
		}
		ttl := defaults.TTL
		if member.Member.TTL != nil {
			ttl = *member.Member.TTL
		}
		fmt.Fprintf(&output, "    ttl: %d\n", ttl)
	}

	pinned := groupMembers(members, func(member resolvedMember) bool {
		return member.Placement == "resident" && member.Layout.Role == "coder"
	})
	utilities := groupMembers(members, func(member resolvedMember) bool {
		return member.Placement == "resident" && member.Layout.Role != "coder"
	})
	heavy := groupMembers(members, func(member resolvedMember) bool {
		return member.Placement == "on_demand"
	})
	if len(pinned)+len(utilities)+len(heavy) > 0 {
		output.WriteString("\nrouting:\n  router:\n    use: group\n    settings:\n      groups:\n")
		if len(pinned) > 0 {
			output.WriteString("        pinned:            # resident coders\n")
			output.WriteString("          persistent: true\n          swap: false\n          exclusive: false\n")
			fmt.Fprintf(&output, "          members: %s\n", yamlStringList(pinned))
		}
		if len(utilities) > 0 {
			output.WriteString("        utilities:         # resident specialists\n")
			output.WriteString("          persistent: true\n          swap: false\n          exclusive: false\n")
			fmt.Fprintf(&output, "          members: %s\n", yamlStringList(utilities))
		}
		if len(heavy) > 0 {
			output.WriteString("        heavy:              # on-demand members\n")
			output.WriteString("          swap: true\n          exclusive: false\n")
			fmt.Fprintf(&output, "          members: %s\n", yamlStringList(heavy))
		}
	}
	return []byte(output.String())
}

func llamaCommand(member resolvedMember) []string {
	layout := member.Layout
	lines := []string{
		"llama-server --port ${PORT}",
		"-m " + shellQuote(member.ModelPath),
		"--offline",
		"--no-mmproj",
	}
	if layout.Role == "rerank" {
		lines = append(lines, "--reranking")
	} else {
		lines = append(lines, "--jinja")
	}
	lines = append(lines,
		fmt.Sprintf("--parallel %d", layout.Llama.Parallel),
		fmt.Sprintf("-c %d", layout.Window),
		fmt.Sprintf("-fa %s", layout.Llama.FlashAttention),
	)
	if layout.Role == "coder" {
		kv := "f16"
		if layout.KV == "q8" {
			kv = "q8_0"
		}
		lines = append(lines, fmt.Sprintf("-ctk %s -ctv %s", kv, kv))
	}
	lines = append(lines,
		fmt.Sprintf("-b %d", layout.Llama.Batch),
		fmt.Sprintf("-ub %d", layout.Llama.UBatch),
	)
	if member.PatchPath != "" {
		lines = append(lines, "--chat-template-file "+shellQuote(member.PatchPath))
	}
	if layout.Role == "coder" {
		lines = append(lines, fmt.Sprintf("--chat-template-kwargs '{\"enable_thinking\":%t}'", layout.Thinking == "on"))
	}
	if member.Member.NGL != nil {
		lines = append(lines, fmt.Sprintf("-ngl %d", *member.Member.NGL))
	}
	return lines
}

type piCost struct {
	Input      int `json:"input"`
	Output     int `json:"output"`
	CacheRead  int `json:"cacheRead"`
	CacheWrite int `json:"cacheWrite"`
}

type piModel struct {
	ID            string   `json:"id"`
	Name          string   `json:"name"`
	Reasoning     bool     `json:"reasoning"`
	Input         []string `json:"input"`
	ContextWindow int      `json:"contextWindow"`
	MaxTokens     int      `json:"maxTokens"`
	Cost          piCost   `json:"cost"`
}

type piCompatibility struct {
	SupportsDeveloperRole   bool `json:"supportsDeveloperRole"`
	SupportsReasoningEffort bool `json:"supportsReasoningEffort"`
}

type piProvider struct {
	BaseURL string          `json:"baseUrl"`
	API     string          `json:"api"`
	APIKey  string          `json:"apiKey"`
	Compat  piCompatibility `json:"compat"`
	Models  []piModel       `json:"models"`
}

func renderPiModels(base []byte, members []resolvedMember) ([]byte, error) {
	root, err := decodeJSONObject(base)
	if err != nil {
		return nil, err
	}
	providers, err := objectAt(root, "providers")
	if err != nil {
		return nil, err
	}

	var models []piModel
	for _, member := range members {
		if member.Layout.Role != "coder" {
			continue
		}
		models = append(models, piModel{
			ID:            member.ID,
			Name:          member.Layout.DisplayName,
			Reasoning:     member.Layout.Thinking == "on",
			Input:         []string{"text"},
			ContextWindow: member.Layout.Window,
			MaxTokens:     member.Layout.MaxTokens,
			Cost:          piCost{},
		})
	}
	providers["local"] = piProvider{
		BaseURL: "http://localhost:8080/v1",
		API:     "openai-completions",
		APIKey:  "local",
		Compat: piCompatibility{
			SupportsDeveloperRole:   false,
			SupportsReasoningEffort: false,
		},
		Models: models,
	}
	root["providers"] = providers
	root["_generated_by"] = "temper — the local provider is generated from manifest.yaml"
	return marshalJSON(root)
}

func renderPiSettings(base []byte, members []resolvedMember) ([]byte, error) {
	root, err := decodeJSONObject(base)
	if err != nil {
		return nil, err
	}
	for _, member := range members {
		if member.Member.Preferred {
			root["defaultModel"] = member.ID
			break
		}
	}
	compaction, err := objectAt(root, "compaction")
	if err != nil {
		return nil, err
	}
	if value, exists := compaction["enabled"]; exists {
		enabled, ok := value.(bool)
		if !ok {
			return nil, errors.New("base field \"compaction.enabled\" must be a boolean")
		}
		if !enabled {
			return marshalJSON(root)
		}
	}

	window := 0
	for _, member := range members {
		if member.Placement != "resident" || member.Layout.Role != "coder" {
			continue
		}
		if window == 0 || member.Layout.Window < window {
			window = member.Layout.Window
		}
	}
	if window == 0 {
		return nil, errors.New("pi needs a resident coder from which to derive compaction")
	}
	reserve := window / 8
	compaction["reserveTokens"] = reserve
	compaction["keepRecentTokens"] = (window - reserve) / 3
	root["compaction"] = compaction
	return marshalJSON(root)
}

func decodeJSONObject(data []byte) (map[string]any, error) {
	if len(bytes.TrimSpace(data)) == 0 {
		return map[string]any{}, nil
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	var root map[string]any
	if err := decoder.Decode(&root); err != nil {
		return nil, fmt.Errorf("base is not valid JSON: %w", err)
	}
	var extra any
	if err := decoder.Decode(&extra); err == nil {
		return nil, errors.New("base contains more than one JSON value")
	} else if !errors.Is(err, io.EOF) {
		return nil, fmt.Errorf("read base JSON: %w", err)
	}
	if root == nil {
		return nil, errors.New("base must be a JSON object")
	}
	return root, nil
}

func objectAt(root map[string]any, key string) (map[string]any, error) {
	value, ok := root[key]
	if !ok || value == nil {
		return map[string]any{}, nil
	}
	object, ok := value.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("base field %q must be an object", key)
	}
	return object, nil
}

func marshalJSON(value any) ([]byte, error) {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("encode JSON: %w", err)
	}
	return append(data, '\n'), nil
}

func groupMembers(members []resolvedMember, include func(resolvedMember) bool) []string {
	var ids []string
	for _, member := range members {
		if include(member) {
			ids = append(ids, member.ID)
		}
	}
	return ids
}

func yamlStringList(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, strconv.Quote(value))
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
}

func contains(values []string, wanted string) bool {
	for _, value := range values {
		if value == wanted {
			return true
		}
	}
	return false
}

type hashWriter interface {
	Write([]byte) (int, error)
}

func writeHashPart(writer hashWriter, data []byte) {
	var size [8]byte
	binary.BigEndian.PutUint64(size[:], uint64(len(data)))
	_, _ = writer.Write(size[:])
	_, _ = writer.Write(data)
}
